apiVersion: 1

datasources:
{% for host in groups['honeypots'] %}
  - name: Prometheus ({{ hostvars[host].inventory_hostname }}) 
    type: prometheus
    access: proxy
    url: http://{{ hostvars[host].ansible_host }}:9090
{% endfor %}

  - name: Loki
    type: loki
    access: proxy
    url: http://localhost:3100
    jsonData:
      timeout: 60
      maxLines: 1000

