- name: Update package lists and install apt-transport-https
  become: true
  ansible.builtin.apt:
    name: apt-transport-https
    state: present
    update_cache: true
    
- name: Retrieve Grafana repository signing key
  become: true
  ansible.builtin.get_url:
    url: https://apt.grafana.com/gpg.key
    dest: /etc/apt/keyrings/grafana.asc
    checksum: sha256:58052c148058ace26dbd01ce057afa5709fb9d39c8a8ab16800be3f42fc02ab2

- name: Add Grafana repository to apt sources
  become: true
  ansible.builtin.deb822_repository:
    name: grafana
    types: deb
    uris: https://apt.grafana.com
    suites: stable
    components:
      - main
    signed_by: /etc/apt/keyrings/grafana.asc

- name: Update package lists and install alloy
  become: true
  ansible.builtin.apt:
    name: alloy
    state: present
    update_cache: true

- name: Install alloy configuration file
  become: true
  ansible.builtin.template:
    src: config.alloy
    dest: /etc/alloy/config.alloy
    owner: alloy
    group: alloy
    mode: '0600'
    backup: true

- name: Restart and enable alloy service
  become: true
  ansible.builtin.service:
    name: alloy
    state: restarted
    enabled: true



