global:
  scrape_interval: 15s

scrape_configs:
  - job_name: sshesame
    static_configs:
      - targets: ['localhost:2112']

  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']

  - job_name: node-exporter
    static_configs:
      - targets: ['localhost:9100']
